apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor-role-bind
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: executor
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
  - kind: ServiceAccount
    name: volcano-executor-plugin
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor
  annotations:
    workflows.argoproj.io/description: |
      Recommended minimum permissions for the `docker` executor.
      This executor is superseded by  the `emmisary` executor, so we do not recommend you use it anymore.
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
      - workflowtasksets/status
    verbs:
      - create
      - patch

