# 定义docker_tag镜像版本号
# 研测基于CI_PIPELINE_ID
# 上线基于branch日期版本
variables:
  docker_tag : v$CI_PIPELINE_ID

# 定义Pipeline过程
stages:
- build
before_script:
  - docker info
  - docker login -u $CI_DOCKER_USERNAME -p $CI_DOCKER_PASSWORD artifacts.iflytek.com/docker-private


# 研测环境基于develop分支自动CI
tag-release:
  stage: build
  script:
    - docker build  -t artifacts.iflytek.com/docker-private/atp/argo-volcano-executor-plugin:"$CI_COMMIT_TAG" . -f Dockerfile_iflytek
    - docker push artifacts.iflytek.com/docker-private/atp/argo-volcano-executor-plugin:"$CI_COMMIT_TAG"
  only:
    - tags
  tags:
    - k8s
# 研测环境基于develop分支自动CI
test-build-dev:
  stage: build
  script:
    - docker build  -t artifacts.iflytek.com/docker-private/atp/argo-volcano-executor-plugin:"$docker_tag" . -f Dockerfile_iflytek
    - docker push artifacts.iflytek.com/docker-private/atp/argo-volcano-executor-plugin:"$docker_tag"
  only:
    - master
  tags:
  - k8s


